{{- if .Values.apptest.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "preflight.fullname" . }}-tester
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    marketplace.cloud.google.com/verification: "test"
  labels:
    {{- include "preflight.labels" . | nindent 4 }}
spec:
  restartPolicy: Never
  containers:
    - name: tester
      image: {{ include "preflight.image" .Values.apptest.image | quote }}
      imagePullPolicy: {{ .Values.apptest.image.pullPolicy }}
      env:
        - name: APP_BASE_URL
          value: {{ printf "http://%s.%s.svc.cluster.local:%v" (include "preflight.fullname" .) .Release.Namespace .Values.service.port | quote }}
        - name: APP_INSTANCE_NAME
          value: {{ include "preflight.fullname" . | quote }}
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
{{- end }}
