{{- if .Values.billing.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-ubbagent" (include "preflight.fullname" .) | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "preflight.labels" . | nindent 4 }}
data:
  config.yaml: |
    identities:
      - name: gcp
        gcp:
          encodedServiceAccountKey: ${MARKETPLACE_REPORTING_KEY_B64}
    metrics:
      - name: {{ .Values.billing.ubbagent.metricNameStandard | quote }}
        type: int
        endpoints:
          - name: servicecontrol
      - name: {{ .Values.billing.ubbagent.metricNameDeep | quote }}
        type: int
        endpoints:
          - name: servicecontrol
    endpoints:
      - name: servicecontrol
        servicecontrol:
          identity: gcp
          serviceName: {{ .Values.billing.ubbagent.serviceName | quote }}
          consumerId: ${MARKETPLACE_CONSUMER_ID}
{{- end }}
