image:
  repository: us-docker.pkg.dev/glassbox-bio-public/glassbox-bio-preflight-ui-hub/glassbox-preflight
  tag: 20260321-223300

auth:
  tokensJson: |
    [{"token":"replace-me","user":"customer-admin","role":"admin"}]

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: false

storage:
  type: pvc
  pvc:
    size: 20Gi
    accessMode: ReadWriteOnce
    storageClassName: ""

app:
  publicVerification: true
  publicAppUrl: ""
  publicApiUrl: ""
  entitlementUrl: ""
  entitlementAuthMode: ""
  runnerImage: us-docker.pkg.dev/glassbox-bio-public/glassbox-bio-molecular-audit/glassbox-mol-audit:1.0.0
  runnerServiceAccount: ""

runtimeTools:
  enabled: true
  kubectlVersion: v1.35.3
  helmVersion: v4.0.1
