{{- if not .Values.app.authDisabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-auth" (include "preflight.fullname" .) | quote }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "preflight.labels" . | nindent 4 }}
type: Opaque
stringData:
  K8S_API_TOKEN: {{ .Values.app.authToken | quote }}
{{- end }}
